/* Cross-language golden parity, from C.
 *
 * Load each committed case's dataset under its spec, seek to the blessed
 * instant (or play the blessed range) and assert the response equals
 * golden/expected/<spec>.json byte-for-byte. The ABI returns the core's compact
 * command output verbatim, so byte equality is the exact cross-language parity
 * check — the same one Python, Node, Go, C#, Java, R and WASM make.
 *
 * The case table is here rather than globbed, because a case is more than a
 * spec: it names a dataset and an instant too, and those pairings live in
 * golden/README.md. `golden_cases.h` is still generated by CMake, and the
 * `every_case_is_covered` check below fails if the corpus grows a spec this
 * table does not carry — so a new case cannot be silently skipped.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "wickra_timemachine.h"

#include "golden_cases.h" /* GOLDEN_DIR, GOLDEN_CASES, GOLDEN_CASE_COUNT */

/* dataset, spec stem, the command to send. */
typedef struct {
    const char *dataset;
    const char *spec;
    const char *command;
} Case;

static const Case CASES[] = {
    {"mini", "mini", "{\"cmd\":\"seek\",\"ts\":1700000600}"},
    {"mini", "funding", "{\"cmd\":\"seek\",\"ts\":1700000700}"},
    {"multi", "multi_symbol", "{\"cmd\":\"seek\",\"ts\":1700000600}"},
    {"mini", "anchor_reseek", "{\"cmd\":\"seek\",\"ts\":1700000500}"},
    {"mini", "play", "{\"cmd\":\"play\",\"from\":1700000000,\"to\":1700000700,\"step\":100}"},
};
static const size_t CASE_COUNT = sizeof(CASES) / sizeof(CASES[0]);

/* Read a whole file. Caller frees. */
static char *slurp(const char *path) {
    FILE *file = fopen(path, "rb");
    if (!file) {
        fprintf(stderr, "cannot open %s\n", path);
        return NULL;
    }
    if (fseek(file, 0, SEEK_END) != 0) {
        fclose(file);
        return NULL;
    }
    long size = ftell(file);
    if (size < 0 || fseek(file, 0, SEEK_SET) != 0) {
        fclose(file);
        return NULL;
    }
    char *buf = (char *)malloc((size_t)size + 1);
    if (!buf) {
        fclose(file);
        return NULL;
    }
    size_t got = fread(buf, 1, (size_t)size, file);
    fclose(file);
    buf[got] = '\0';
    return buf;
}

/* Trim ASCII whitespace in place; returns the start of the trimmed text. */
static char *trim(char *text) {
    while (*text == ' ' || *text == '\n' || *text == '\r' || *text == '\t') {
        text++;
    }
    size_t len = strlen(text);
    while (len > 0) {
        char last = text[len - 1];
        if (last != ' ' && last != '\n' && last != '\r' && last != '\t') {
            break;
        }
        text[--len] = '\0';
    }
    return text;
}

/* The feed as a JSON string literal: the newlines separating JSONL records have
 * to be escaped to cross the command boundary. Caller frees. */
static char *as_json_string(const char *raw) {
    size_t cap = strlen(raw) * 2 + 3;
    char *out = (char *)malloc(cap);
    if (!out) {
        return NULL;
    }
    size_t j = 0;
    out[j++] = '"';
    for (size_t i = 0; raw[i] != '\0'; i++) {
        char c = raw[i];
        if (c == '\n') {
            out[j++] = '\\';
            out[j++] = 'n';
        } else if (c == '\r') {
            continue;
        } else if (c == '"' || c == '\\') {
            out[j++] = '\\';
            out[j++] = c;
        } else {
            out[j++] = c;
        }
    }
    out[j++] = '"';
    out[j] = '\0';
    return out;
}

/* Run one command through the two-call idiom. Caller frees. */
static char *run(WickraTimeMachine *tm, const char *cmd) {
    int32_t len = wickra_timemachine_command(tm, cmd, NULL, 0);
    if (len < 0) {
        return NULL;
    }
    char *buf = (char *)malloc((size_t)len + 1);
    if (!buf) {
        return NULL;
    }
    if (wickra_timemachine_command(tm, cmd, buf, (size_t)len + 1) != len) {
        free(buf);
        return NULL;
    }
    return buf;
}

static char *path3(const char *a, const char *b, const char *c) {
    size_t len = strlen(a) + strlen(b) + strlen(c) + 1;
    char *out = (char *)malloc(len);
    if (out) {
        snprintf(out, len, "%s%s%s", a, b, c);
    }
    return out;
}

/* Every spec in the corpus appears in CASES, so a new one cannot be skipped. */
static int every_case_is_covered(void) {
    int missing = 0;
    for (size_t i = 0; i < GOLDEN_CASE_COUNT; i++) {
        int found = 0;
        for (size_t j = 0; j < CASE_COUNT; j++) {
            if (strcmp(GOLDEN_CASES[i], CASES[j].spec) == 0) {
                found = 1;
                break;
            }
        }
        if (!found) {
            fprintf(stderr,
                    "golden/specs/%s.json is in the corpus but not in this test's case table\n",
                    GOLDEN_CASES[i]);
            missing++;
        }
    }
    return missing;
}

int main(void) {
    if (GOLDEN_CASE_COUNT == 0) {
        fprintf(stderr, "no golden specs were configured; this would test nothing\n");
        return 1;
    }
    int failures = every_case_is_covered();

    for (size_t i = 0; i < CASE_COUNT; i++) {
        const Case *c = &CASES[i];

        char *spec_path = path3(GOLDEN_DIR "/specs/", c->spec, ".json");
        char *feed_path = path3(GOLDEN_DIR "/data/", c->dataset, "/events.jsonl");
        char *expected_path = path3(GOLDEN_DIR "/expected/", c->spec, ".json");
        char *spec = spec_path ? slurp(spec_path) : NULL;
        char *feed = feed_path ? slurp(feed_path) : NULL;
        char *expected_raw = expected_path ? slurp(expected_path) : NULL;
        free(spec_path);
        free(feed_path);
        free(expected_path);

        if (!spec || !feed || !expected_raw) {
            fprintf(stderr, "%s: incomplete case\n", c->spec);
            failures++;
            free(spec);
            free(feed);
            free(expected_raw);
            continue;
        }

        WickraTimeMachine *tm = wickra_timemachine_new(spec);
        char *quoted = tm ? as_json_string(feed) : NULL;
        char *load = NULL;
        if (quoted) {
            size_t cap = strlen(quoted) + 32;
            load = (char *)malloc(cap);
            if (load) {
                snprintf(load, cap, "{\"cmd\":\"load\",\"data\":%s}", quoted);
            }
        }
        char *ack = load ? run(tm, load) : NULL;
        char *got_raw = ack ? run(tm, c->command) : NULL;

        if (!got_raw) {
            fprintf(stderr, "%s: command failed\n", c->spec);
            failures++;
        } else {
            char *got = trim(got_raw);
            char *expected = trim(expected_raw);
            if (strcmp(got, expected) != 0) {
                fprintf(stderr, "%s: mismatch\n  expected: %.120s\n  got:      %.120s\n",
                        c->spec, expected, got);
                failures++;
            }
        }

        free(got_raw);
        free(ack);
        free(load);
        free(quoted);
        wickra_timemachine_free(tm);
        free(spec);
        free(feed);
        free(expected_raw);
    }

    if (failures > 0) {
        fprintf(stderr, "%d of %zu golden cases did not match\n", failures, CASE_COUNT);
        return 1;
    }
    printf("all %zu golden cases are byte-identical from C\n", CASE_COUNT);
    return 0;
}
