/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** A recorded-market time machine driven by JSON commands. */
export declare class TimeMachine {
  /** Construct a handle from a spec JSON (`"{}"` uses the default spec). */
  constructor(specJson: string)
  /**
   * Apply a command envelope (`{"cmd":"...", ...}`) and return the response
   * JSON. Commands: `load`, `seek`, `play`, `state_at`, `version`.
   */
  command(cmdJson: string): string
  /** The crate version. */
  version(): string
}
