/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A recorded-market time machine driven by JSON commands. */
export declare class TimeMachine {
  /** Construct a handle from a spec JSON (`"{}"` uses the default spec). */
  constructor(specJson: string)
  /**
   * Apply a command envelope (`{"cmd":"...", ...}`) and return the response
   * JSON. Commands: `load`, `seek`, `play`, `state_at`, `version`.
   */
  command(cmdJson: string): string
  /** The crate version. */
  version(): string
}
